### ISSUE TITLE
<pre>usage: get_ecb_data.py [-h] [--data_path DATA_PATH] [--output_dir OUTPUT_DIR] get_ecb_data.py: error: unrecognized arguments: 

### ISSUE THREAD

**Issue by kusumlata123** [ariecattan/coref#4]
python get_ecb_data.py --/home/dr/Desktop/corefecb/data /home/dr/Desktop/corefecb
2022-01-03 16:54:15.600300: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
usage: get_ecb_data.py [-h] [--data_path DATA_PATH] [--output_dir OUTPUT_DIR]
get_ecb_data.py: error: unrecognized arguments: --/home/dr/Desktop/corefecb/data /home/dr/Desktop/corefecb
 why am i getting this error

**Comment by ariecattan** [comment]
you should specify the names of the arguments `--data_path` and `--output_dir`
